// Auto-generated by training/04_export_c.py - do not edit.
#pragma once
#define HAR_FS_HZ 50
#define HAR_WINDOW 128
#define HAR_HOP 64
#define HAR_N_CH 6
#define HAR_N_CLASSES 6
static const char* HAR_CLASSES[HAR_N_CLASSES] = {"WALKING", "WALKING_UPSTAIRS", "WALKING_DOWNSTAIRS", "SITTING", "STANDING", "LAYING"};
// per-channel standardisation computed on the TRAIN subjects (ax ay az [g], gx gy gz [rad/s])
static const float HAR_MEAN[HAR_N_CH] = {0.797936f, 0.033838f, 0.093247f, 0.001410f, -0.000798f, -0.000134f};
static const float HAR_STD[HAR_N_CH]  = {0.416971f, 0.388060f, 0.368321f, 0.406633f, 0.380228f, 0.259465f};
