"""Step 4: export artefacts for the ESP32 firmware.

  firmware/esp32_har/model_data.h   - both .tflite blobs as const uint8_t arrays (flash)
  firmware/esp32_har/har_config.h   - class names, per-channel mean/std, window/rate constants
  firmware/esp32_har/test_windows.h - REPLAY windows from held-out TEST subjects (raw g / rad/s),
                                      so the on-device demo runs the full preprocessing path.
"""
import os, numpy as np
from common import *
set_seed()

d = np.load(os.path.join(RESULTS, "dataset.npz"))
Xte, yte, ste = d["Xte"], d["yte"], d["subj_te"]
mean, std = d["mean"], d["std"]
PER_CLASS = 3

def c_array(name, blob):
    lines = [f"alignas(16) const unsigned char {name}[] = {{"]
    for i in range(0, len(blob), 16):
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in blob[i:i+16]) + ",")
    lines.append("};"); lines.append(f"const unsigned int {name}_len = {len(blob)};")
    return "\n".join(lines)

f32 = open(os.path.join(RESULTS, "har_float32.tflite"), "rb").read()
i8 = open(os.path.join(RESULTS, "har_int8.tflite"), "rb").read()
os.makedirs(FIRMWARE, exist_ok=True)
with open(os.path.join(FIRMWARE, "model_data.h"), "w") as f:
    f.write("// Auto-generated by training/04_export_c.py - do not edit.\n#pragma once\n")
    f.write("// float32 baseline model (before optimisation)\n" + c_array("har_float32_tflite", f32) + "\n\n")
    f.write("// int8 full-integer PTQ model (after optimisation)\n" + c_array("har_int8_tflite", i8) + "\n")

with open(os.path.join(FIRMWARE, "har_config.h"), "w") as f:
    f.write("// Auto-generated by training/04_export_c.py - do not edit.\n#pragma once\n")
    f.write(f"#define HAR_FS_HZ {FS_HZ}\n#define HAR_WINDOW {WINDOW}\n#define HAR_HOP {HOP}\n#define HAR_N_CH {N_CH}\n#define HAR_N_CLASSES {len(CLASSES)}\n")
    f.write("static const char* HAR_CLASSES[HAR_N_CLASSES] = {" + ", ".join(f'"{c}"' for c in CLASSES) + "};\n")
    f.write("// per-channel standardisation computed on the TRAIN subjects (ax ay az [g], gx gy gz [rad/s])\n")
    f.write("static const float HAR_MEAN[HAR_N_CH] = {" + ", ".join(f"{v:.6f}f" for v in mean) + "};\n")
    f.write("static const float HAR_STD[HAR_N_CH]  = {" + ", ".join(f"{v:.6f}f" for v in std) + "};\n")

rng = np.random.default_rng(SEED)
sel = np.concatenate([rng.choice(np.where(yte == c)[0], PER_CLASS, replace=False) for c in range(len(CLASSES))])
with open(os.path.join(FIRMWARE, "test_windows.h"), "w") as f:
    f.write("// Auto-generated by training/04_export_c.py - do not edit.\n#pragma once\n#include \"har_config.h\"\n")
    f.write(f"#define N_TEST_WINDOWS {len(sel)}\n")
    f.write("static const uint8_t TEST_LABELS[N_TEST_WINDOWS] = {" + ", ".join(str(int(yte[i])) for i in sel) + "};\n")
    f.write("static const uint8_t TEST_SUBJECTS[N_TEST_WINDOWS] = {" + ", ".join(str(int(ste[i])) for i in sel) + "};\n")
    f.write("// raw sensor values, shape [window][sample][channel]\n")
    f.write("static const float TEST_WINDOWS[N_TEST_WINDOWS][HAR_WINDOW][HAR_N_CH] PROGMEM = {\n")
    for i in sel:
        f.write("  {\n" + "".join("    {" + ", ".join(f"{v:.5f}f" for v in row) + "},\n" for row in Xte[i]) + "  },\n")
    f.write("};\n")
save_json({"replay_test_indices": [int(i) for i in sel], "labels": [int(yte[i]) for i in sel]}, "replay_windows.json")
print(f"exported {len(f32)} B float32, {len(i8)} B int8, {len(sel)} replay windows")
