"""Step 7: collect every number reported in the report into results/summary.md."""
import os
from common import *
di, tr, q = load_json("dataset_info.json"), load_json("train_float32.json"), load_json("quantization.json")
dev = load_json("device_metrics.json")
f, i = q["float32"], q["int8_ptq"]; m = dev["models"]
L = []
L += ["# Results summary (auto-generated by training/07_summary.py)", "",
      "## Data", f"- windows: train {di['train_windows']} / val {di['val_windows']} / test {di['test_windows']} "
      f"(subjects {len(di['train_subjects'])}/{len(di['val_subjects'])}/{len(di['test_subjects'])}, no overlap)",
      f"- window {di['window']} samples @ {di['fs_hz']} Hz = {di['window']/di['fs_hz']:.2f} s, hop {di['hop']} (50 % overlap), 6 channels", "",
      "## Model", f"- float32 1D-CNN, {tr['params']} parameters, trained {tr['epochs_run']} epochs in {tr['train_time_s']:.1f} s (GPU), seed {SEED}", "",
      "## Before / after post-training int8 quantisation", "",
      "| metric | float32 (before) | int8 PTQ (after) | change |", "|---|---|---|---|",
      f"| test accuracy (9 unseen subjects, n={di['test_windows']}) | {f['test_accuracy']*100:.2f} % | {i['test_accuracy']*100:.2f} % | {q['accuracy_delta']*100:+.2f} pt |",
      f"| macro-F1 | {f['macro_f1']:.4f} | {i['macro_f1']:.4f} | {i['macro_f1']-f['macro_f1']:+.4f} |",
      f"| prediction agreement float vs int8 | - | {q['prediction_agreement']*100:.2f} % | |",
      f"| weight bytes (params x dtype) | {tr['params']*4} B | {tr['params']} B | 4.00x smaller |",
      f"| .tflite file (flash) | {f['size_bytes']} B | {i['size_bytes']} B | {q['size_reduction_x']:.2f}x smaller |",
      f"| tensor arena used (ESP32 RAM) | {m['float32']['arena_used_bytes']} B | {m['int8']['arena_used_bytes']} B | {m['float32']['arena_used_bytes']/m['int8']['arena_used_bytes']:.2f}x smaller |",
      f"| on-device accuracy, 18 replay windows | {dev['f32_on_device_acc']*100:.1f} % | {dev['int8_on_device_acc']*100:.1f} % | |",
      f"| host-vs-device prediction agreement | {dev['host_device_agreement']['float32']*100:.1f} % | {dev['host_device_agreement']['int8']*100:.1f} % | |",
      f"| inference latency, Wokwi ESP32 @240 MHz, -O2 (mean of 18) | {dev['f32_latency']['mean_us']/1000:.1f} ms | {dev['int8_latency']['mean_us']/1000:.1f} ms | {dev['speedup_x']:.2f}x (int8 SLOWER in Wokwi, see report) |",
      "", "## Sensing pipeline (measured on device)",
      f"- measured sampling rate in LIVE mode: {', '.join(f'{r:.1f}' for r in dev['live_measured_rate_hz'])} Hz (nominal 50 Hz), 0 missed deadlines, 0 dropped windows",
      "", "## PTQ settings", *[f"- {k}: {v}" for k, v in q["settings"].items()],
      f"- input quantisation: scale={i['input_quant'][0]:.5f}, zero_point={int(i['input_quant'][1])}; output scale={i['output_quant'][0]}, zero_point={int(i['output_quant'][1])}",
      "", "## Per-layer weight ranges (outlier check)", "| layer | n | min | max | max|w|/std | int8 step |", "|---|---|---|---|---|---|",
      *[f"| {l['layer']} | {l['n']} | {l['min']:.3f} | {l['max']:.3f} | {l['max_abs_over_std']:.2f} | {l['int8_step']:.4f} |" for l in q["layer_weight_stats"]]]
open(os.path.join(RESULTS, "summary.md"), "w").write("\n".join(L) + "\n")
print("\n".join(L))
